# Generated by Django 5.2.6 on 2025-09-19 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "jti",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revoked", models.BooleanField(default=False)),
                ("replaced_by", models.UUIDField(blank=True, null=True)),
                ("device_info", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Refresh Token",
                "verbose_name_plural": "Refresh Tokens",
                "db_table": "refresh_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="refresh_tok_user_id_46676d_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="refresh_tok_expires_a128d9_idx"
                    ),
                    models.Index(
                        fields=["revoked"], name="refresh_tok_revoked_3e6e61_idx"
                    ),
                ],
            },
        ),
    ]
